### ISSUE TITLE
Can I export the gitbook into pdf version?

### ISSUE THREAD

**Issue by hsiaoyi0504** [msperlin/pafdR#1]
As title, I think it would be helpful to help much more people if the pdf version is available. Can I export the gitbook into pdf version?

**Comment by msperlin** [comment]
Hi Hsiao,

Sorry but I rather just keep the online html version as I can update it easilly. You can, however, print the html files for each chapter in chrome. 

Best,

**Comment by hsiaoyi0504** [comment]
Hi, sorry for late reply. Actually, what I want to ask is that if I can export the pdf version and distribute to public. Why I ask this is because I think this may affect your profits.

**Comment by msperlin** [comment]
Hi Hsiao, 

Yes, you can export the pdf from the html and distribute . Just make sure you provide the actual link to the online book.
